config/routes.rb
Pinteresting::Application.routes.draw do
  resources :feeds

  devise_for :users

  root 'feeds#index'

  get "about" => "pages#about"

end

app/models/feed.rb
class Feed < ActiveRecord::Base
	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :last_name, presence: true
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
require 'twitter'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller? 
  before_filter :initialize_twitter
  protected

	def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :first_name
  	devise_parameter_sanitizer.for(:account_update) << :first_name
  	devise_parameter_sanitizer.for(:sign_up) << :last_name
  	devise_parameter_sanitizer.for(:account_update) << :last_name
	end

  def initialize_twitter
    @twitter_client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
      config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
    end
  end
  
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    @tweets = @twitter_client.user_timeline("konathamrajesh")
  end
  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.all.build
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.all.build(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
	
	def settings
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/feeds/_form.html.erb
<%= form_for @feed , html: { multipart: true } do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
		<h1>Editing feed</h1>
  </div>
  <div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Show', @feed %> |
		<%= link_to 'Back', feeds_path %>
	</div>
</div>

app/views/feeds/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div id="feeds" class="transitions-enabled">
  <% @feeds.each do |feed| %>
    <div class="box panel panel-default">
    	<%= link_to feed.content, class: "iframe cboxElement" do %>
	      <div class="panel-heading center">
	        <p><strong><%= feed.title %></strong></p>
	      </div>
    	<% end %>
      <div class="panel-body">
        <p><%= render inline: feed.summary %></p>
      </div>
    </div>
  <% end %>
</div>
<div class="center">
   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/feeds/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  	<h1>New feed</h1>
  </div>
  <div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back', feeds_path %>
	</div>
</div>

app/views/feeds/show.html.erb
<%= link_to 'Back', feeds_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <p><strong><%= @feed.title %></strong></p>
      </div>
      <div class="panel-body">
        <p><strong><%= render inline: feed.summary %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "FeedCanvas", root_path,class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Settings<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                  <span class="glyphicon glyphicon-user"></span> Account Settings
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-off"></span> Log out
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to  destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-plus"></span> Add Feed Source
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedCanvas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render "layouts/navbar" %> 
	<div class="container"> 
		<% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
	<div class="jumbotron center">
		<h1>Welcome to my app!</h1>
		<p>
  		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
  		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
 		</p>
	</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<p>We are working on a app to show all your feeds!</p>
</div>


app/views/pages/settings.html.erb
<h1>Pages#settings</h1>
<p>Find me in app/views/pages/settings.html.erb</p>